package view;

public enum SpecialMove {
    FALSE,
    CASTLE_SHORT, CASTLE_LONG, EN_PASSANT,
    PROMOTION_KNIGHT_WHITE, PROMOTION_KNIGHT_BLACK,
    PROMOTION_BISHOP_WHITE, PROMOTION_BISHOP_BLACK,
    PROMOTION_ROOK_WHITE, PROMOTION_ROOK_BLACK,
    PROMOTION_QUEEN_WHITE, PROMOTION_QUEEN_BLACK;
}
